import os
import subprocess
from datetime import datetime

def escape_latex(text):
    replacements = {
        '&': r'\&',
        '%': r'\%',
        '$': r'\$',
        '#': r'\#',
        '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\^{}',
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text

def generate_report_pdf(report_content, papers, topic, output_path):
    bibliography = ""
    for i, paper in enumerate(papers, 1):
        title = escape_latex(paper['title'])
        authors_list = paper['authors']
        if len(authors_list) > 3:
            authors = escape_latex(', '.join(authors_list[:3])) + ' et al.'
        else:
            authors = escape_latex(', '.join(authors_list))
        arxiv_id = paper['arxiv_id']
        published = paper['published']
        
        bibliography += f"""\\bibitem{{paper{i}}}
{authors}.
\\textit{{{title}}}.
arXiv:{arxiv_id}, {published}.

"""
    
    latex_content = r"""\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{cite}
\usepackage{abstract}

\title{""" + escape_latex(topic) + r"""}
\author{Generated by Paper Producer}
\date{""" + datetime.now().strftime('%Y-%m-%d') + r"""}

\begin{document}

\maketitle

"""
    
    latex_content += report_content
    
    latex_content += r"""

\begin{thebibliography}{99}
""" + bibliography + r"""\end{thebibliography}

\end{document}
"""
    
    base_path = output_path.replace('.pdf', '')
    tex_file = base_path + '.tex'
    
    with open(tex_file, 'w', encoding='utf-8') as f:
        f.write(latex_content)
    
    work_dir = os.path.dirname(tex_file) or '.'
    tex_filename = os.path.basename(tex_file)
    
    subprocess.run(
        ['pdflatex', '-interaction=nonstopmode', tex_filename],
        cwd=work_dir,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )
    
    subprocess.run(
        ['pdflatex', '-interaction=nonstopmode', tex_filename],
        cwd=work_dir,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )
    
    for ext in ['.aux', '.log', '.out']:
        cleanup_file = base_path + ext
        if os.path.exists(cleanup_file):
            os.remove(cleanup_file)
